package com.lhdb.game.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.lhdb.game.entity.Module;
import com.lhdb.game.entity.ModuleExample;

public interface ModuleMapper {
	
	/**
	 * 设置角色 模块权限
	 * @param moduleid 模块id
	 * @param roleid  角色id
	 * @param permissioncode 权限值
	 * @return
	 */
	Integer setRolePermission(@Param("record") Map<String, Integer> record);
	
	List<Module> getModulePermission(Integer roleid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int countByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByPrimaryKey(Integer moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    Module selectByPrimaryKey(Integer moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExample(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Module
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKey(Module record);
}