package com.lhdb.game.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lhdb.game.entity.ModulePermission;
import com.lhdb.game.entity.ModulePermissionExample;
import com.lhdb.game.entity.ModulePermissionKey;

public interface ModulePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int countByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByPrimaryKey(ModulePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insert(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insertSelective(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    List<ModulePermission> selectByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    ModulePermission selectByPrimaryKey(ModulePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") ModulePermission record, @Param("example") ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExample(@Param("record") ModulePermission record, @Param("example") ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKeySelective(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ModulePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKey(ModulePermission record);
}