package com.lhdb.game.dao;

import com.lhdb.game.entity.OrderDf;
import com.lhdb.game.entity.OrderDfExample;
import com.lhdb.game.entity.OrderInfo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int countByExample(OrderDfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int deleteByExample(OrderDfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int insert(OrderDf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int insertSelective(OrderDf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    List<OrderDf> selectByExample(OrderDfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    OrderDf selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderDf record, @Param("example") OrderDfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int updateByExample(@Param("record") OrderDf record, @Param("example") OrderDfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int updateByPrimaryKeySelective(OrderDf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_df
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    int updateByPrimaryKey(OrderDf record);
    
    List<OrderDf> searchOnPage(OrderInfo orderInfo);
    
    int count(OrderInfo record);
}