package com.lhdb.game.entity;
import java.io.Serializable;
import java.util.List;
import java.util.List;

public class Module implements Serializable{
	/**
	 * 权限列表
	 */
	//private List<ModulePermission> permissions;
	
	/**
	 * 获取权限列表
	 * @return
	 */
//	public List<ModulePermission> getPermissions()
//	{
//		return permissions;
//	}
	/**
	 * 设置权限
	 * @param permissions
	 */
//	public void setPermissions(List<ModulePermission> permissions)
//	{
//		this.permissions = permissions;
//	}
	
	
	public boolean getLeaf(){
		if(parentid==-9999)return true;
		if( children != null && children.size() > 0)
			return false;
		else
			return true;
		/*
		if( parentid != null && parentid > 0)
			
		else
			return false;
		*/
	}
	
	public boolean getExpanded(){
		//if(parentid==-9999)return false;
		//if( parentid != null && parentid > 0)return false;
		if( children != null && children.size() > 0)
			return true;
		else
			return false;
	}
	
	
	public String getText(){
		return title;
	}
	
	
	public Integer getId(){
		if(parentid==-9999)return null;
		return moduleid;
	}
	
	public String getHref(){
		if(link==null)return "";
		if(link.indexOf(".htm")>-1)
			return  link;
		else return "";
	}
	
	public List<Module> children;
	
    public List<Module> getChildren() {
		return children;
	}
    
    
    public void setIcon(String icon) {
		this.icon = icon;
	}

	private String icon;
    
	public String getIcon() {
		return icon;
	}
	
	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer moduleid;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.ParentID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.Title
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.Link
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.OrderNo
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.Nullity
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer nullity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.IsMenu
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.ManagerPopedom
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer managerpopedom;
    
    private String link2;
    
    public Integer permissionValue;
    
    public Integer OperationPermission;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.ModuleID
     *
     * @return the value of Module.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.ModuleID
     *
     * @param moduleid the value for Module.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.ParentID
     *
     * @return the value of Module.ParentID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.ParentID
     *
     * @param parentid the value for Module.ParentID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.Title
     *
     * @return the value of Module.Title
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.Title
     *
     * @param title the value for Module.Title
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.Link
     *
     * @return the value of Module.Link
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.Link
     *
     * @param link the value for Module.Link
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.OrderNo
     *
     * @return the value of Module.OrderNo
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.OrderNo
     *
     * @param orderno the value for Module.OrderNo
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.Nullity
     *
     * @return the value of Module.Nullity
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getNullity() {
        return nullity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.Nullity
     *
     * @param nullity the value for Module.Nullity
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setNullity(Integer nullity) {
        this.nullity = nullity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.IsMenu
     *
     * @return the value of Module.IsMenu
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.IsMenu
     *
     * @param ismenu the value for Module.IsMenu
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setIsmenu(Integer ismenu) {
        this.ismenu = ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.Description
     *
     * @return the value of Module.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.Description
     *
     * @param description the value for Module.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.ManagerPopedom
     *
     * @return the value of Module.ManagerPopedom
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getManagerpopedom() {
        return managerpopedom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.ManagerPopedom
     *
     * @param managerpopedom the value for Module.ManagerPopedom
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setManagerpopedom(Integer managerpopedom) {
        this.managerpopedom = managerpopedom;
    }
    
    public Integer getPermissionValue() {
		return permissionValue;
	}

	public void setPermissionValue(Integer permissionValue) {
		this.permissionValue = permissionValue;
	}

	public Integer getOperationPermission() {
		return OperationPermission;
	}

	public void setOperationPermission(Integer operationPermission) {
		OperationPermission = operationPermission;
	}

	public String getLink2() {
		return link2;
	}

	public void setLink2(String link2) {
		this.link2 = link2;
	}
}