package com.lhdb.game.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.order_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.user_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.money
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.score
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.acc_no
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String accNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.certif_tp
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Byte certifTp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.certif_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String certifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.customer_nm
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String customerNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.state
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private String backIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.create_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_df.update_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.order_id
     *
     * @return the value of order_df.order_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.order_id
     *
     * @param orderId the value for order_df.order_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.user_id
     *
     * @return the value of order_df.user_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.user_id
     *
     * @param userId the value for order_df.user_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.money
     *
     * @return the value of order_df.money
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.money
     *
     * @param money the value for order_df.money
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.score
     *
     * @return the value of order_df.score
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.score
     *
     * @param score the value for order_df.score
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.acc_no
     *
     * @return the value of order_df.acc_no
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.acc_no
     *
     * @param accNo the value for order_df.acc_no
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setAccNo(String accNo) {
        this.accNo = accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.certif_tp
     *
     * @return the value of order_df.certif_tp
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Byte getCertifTp() {
        return certifTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.certif_tp
     *
     * @param certifTp the value for order_df.certif_tp
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setCertifTp(Byte certifTp) {
        this.certifTp = certifTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.certif_id
     *
     * @return the value of order_df.certif_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getCertifId() {
        return certifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.certif_id
     *
     * @param certifId the value for order_df.certif_id
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setCertifId(String certifId) {
        this.certifId = certifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.customer_nm
     *
     * @return the value of order_df.customer_nm
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getCustomerNm() {
        return customerNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.customer_nm
     *
     * @param customerNm the value for order_df.customer_nm
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setCustomerNm(String customerNm) {
        this.customerNm = customerNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.state
     *
     * @return the value of order_df.state
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.state
     *
     * @param state the value for order_df.state
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.ip_address
     *
     * @return the value of order_df.ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.ip_address
     *
     * @param ipAddress the value for order_df.ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.back_ip_address
     *
     * @return the value of order_df.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public String getBackIpAddress() {
        return backIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.back_ip_address
     *
     * @param backIpAddress the value for order_df.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setBackIpAddress(String backIpAddress) {
        this.backIpAddress = backIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.create_time
     *
     * @return the value of order_df.create_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.create_time
     *
     * @param createTime the value for order_df.create_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_df.update_time
     *
     * @return the value of order_df.update_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_df.update_time
     *
     * @param updateTime the value for order_df.update_time
     *
     * @mbggenerated Wed Jul 05 20:25:37 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}