package com.lhdb.game.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class OrderInfo extends BasePojo{
	
	@DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
    private String start;
    
    @DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
    private String end;

	public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.money
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.score
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.state
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private String backIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.update_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.money
     *
     * @return the value of order_info.money
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.money
     *
     * @param money the value for order_info.money
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.score
     *
     * @return the value of order_info.score
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.score
     *
     * @param score the value for order_info.score
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.state
     *
     * @return the value of order_info.state
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.state
     *
     * @param state the value for order_info.state
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ip_address
     *
     * @return the value of order_info.ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ip_address
     *
     * @param ipAddress the value for order_info.ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.back_ip_address
     *
     * @return the value of order_info.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public String getBackIpAddress() {
        return backIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.back_ip_address
     *
     * @param backIpAddress the value for order_info.back_ip_address
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setBackIpAddress(String backIpAddress) {
        this.backIpAddress = backIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.update_time
     *
     * @return the value of order_info.update_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.update_time
     *
     * @param updateTime the value for order_info.update_time
     *
     * @mbggenerated Wed Jul 05 20:48:38 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}