package com.lhdb.game.entity;

public class Roles  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Roles.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Roles.RoleName
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Roles.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Roles.RoleID
     *
     * @return the value of Roles.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Roles.RoleID
     *
     * @param roleid the value for Roles.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Roles.RoleName
     *
     * @return the value of Roles.RoleName
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Roles.RoleName
     *
     * @param rolename the value for Roles.RoleName
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Roles.Description
     *
     * @return the value of Roles.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Roles.Description
     *
     * @param description the value for Roles.Description
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }
}