package com.lhdb.game.entity;

public class RolePermissionKey  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer moduleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.RoleID
     *
     * @return the value of RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.RoleID
     *
     * @param roleid the value for RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.ModuleID
     *
     * @return the value of RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.ModuleID
     *
     * @param moduleid the value for RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }
}