package com.lhdb.game.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lhdb.game.entity.RolePermission;
import com.lhdb.game.entity.RolePermissionExample;
import com.lhdb.game.entity.RolePermissionKey;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    RolePermission selectByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKey(RolePermission record);
}