package com.lhdb.game.entity;

public class RolePermission  {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer moduleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.RoleID
     *
     * @return the value of RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.RoleID
     *
     * @param roleid the value for RolePermission.RoleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.ModuleID
     *
     * @return the value of RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.ModuleID
     *
     * @param moduleid the value for RolePermission.ModuleID
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.ManagerPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Long managerpermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.OperationPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Long operationpermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RolePermission.StateFlag
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    private Integer stateflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.ManagerPermission
     *
     * @return the value of RolePermission.ManagerPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Long getManagerpermission() {
        return managerpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.ManagerPermission
     *
     * @param managerpermission the value for RolePermission.ManagerPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setManagerpermission(Long managerpermission) {
        this.managerpermission = managerpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.OperationPermission
     *
     * @return the value of RolePermission.OperationPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Long getOperationpermission() {
        return operationpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.OperationPermission
     *
     * @param operationpermission the value for RolePermission.OperationPermission
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setOperationpermission(Long operationpermission) {
        this.operationpermission = operationpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RolePermission.StateFlag
     *
     * @return the value of RolePermission.StateFlag
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public Integer getStateflag() {
        return stateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RolePermission.StateFlag
     *
     * @param stateflag the value for RolePermission.StateFlag
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    public void setStateflag(Integer stateflag) {
        this.stateflag = stateflag;
    }
}