package com.lhdb.game.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class MGiveScoreLog extends BasePojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.user_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.master_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private Integer masterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.score
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.reason
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.client_ip
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_give_score_log.create_time
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    private Date createTime;
    
    private Integer type;
    
    private String name;
    
    private String transferName;
    
    @DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
    private String start;
    
    @DateTimeFormat( pattern = "yyyy-MM-dd HH:mm:ss" )
    private String end;

    public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTransferName() {
		return transferName;
	}

	public void setTransferName(String transferName) {
		this.transferName = transferName;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.id
     *
     * @return the value of m_give_score_log.id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.id
     *
     * @param id the value for m_give_score_log.id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.user_id
     *
     * @return the value of m_give_score_log.user_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.user_id
     *
     * @param userId the value for m_give_score_log.user_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.master_id
     *
     * @return the value of m_give_score_log.master_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public Integer getMasterId() {
        return masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.master_id
     *
     * @param masterId the value for m_give_score_log.master_id
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.score
     *
     * @return the value of m_give_score_log.score
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.score
     *
     * @param score the value for m_give_score_log.score
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.reason
     *
     * @return the value of m_give_score_log.reason
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.reason
     *
     * @param reason the value for m_give_score_log.reason
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.client_ip
     *
     * @return the value of m_give_score_log.client_ip
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.client_ip
     *
     * @param clientIp the value for m_give_score_log.client_ip
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_give_score_log.create_time
     *
     * @return the value of m_give_score_log.create_time
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_give_score_log.create_time
     *
     * @param createTime the value for m_give_score_log.create_time
     *
     * @mbggenerated Wed Dec 07 21:17:25 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}