package com.lhdb.game.dao;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.lhdb.game.entity.Roles;
import com.lhdb.game.entity.RolesExample;

public interface RolesMapper {
	int countByRoleID (Integer roleid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int countByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    List<Roles> selectByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    Roles selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByExample(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Roles
     *
     * @mbggenerated Fri Oct 31 15:08:52 CST 2014
     */
    int updateByPrimaryKey(Roles record);
}