package com.lhdb.game.mongo.entity;

import org.springframework.data.annotation.Version;

public class UserBank {
	
    private String _id;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.user_id
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.bank_score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    private Long bankScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_bank.pay_sum
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    private Long paySum;
    
    @Version  
    protected Long version;

    public String get_id() {
		return _id;
	}

	public void set_id(String _id) {
		this._id = _id;
	}

	public UserBank(String _id, Long userId, Long score, Long bankScore, Long paySum) {
		super();
		this._id = _id;
		this.userId = userId;
		this.score = score;
		this.bankScore = bankScore;
		this.paySum = paySum;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.user_id
     *
     * @return the value of user_bank.user_id
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.user_id
     *
     * @param userId the value for user_bank.user_id
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.score
     *
     * @return the value of user_bank.score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.score
     *
     * @param score the value for user_bank.score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.bank_score
     *
     * @return the value of user_bank.bank_score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public Long getBankScore() {
        return bankScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.bank_score
     *
     * @param bankScore the value for user_bank.bank_score
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public void setBankScore(Long bankScore) {
        this.bankScore = bankScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_bank.pay_sum
     *
     * @return the value of user_bank.pay_sum
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public Long getPaySum() {
        return paySum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_bank.pay_sum
     *
     * @param paySum the value for user_bank.pay_sum
     *
     * @mbggenerated Fri Nov 11 11:21:30 CST 2016
     */
    public void setPaySum(Long paySum) {
        this.paySum = paySum;
    }
}